### ISSUE TITLE
Wagtail 2.9 support

### ISSUE THREAD

**Issue by sonnybaker** [mwesterhof/wagtail_app_pages#10]
* Wagtail App Pages version: 0.2.14
* Wagtail version: 2.9
* Python version: 3.6.9
* Operating System: Ubuntu

### Description
It's not possible to update a site that uses Wagtail App Pages to version 2.9 of Wagtail because the dependencies specify `wagtail >=1.11.1,<2.9`:

Is there anything blocking App Pages working with Wagtail 2.9, or any way I can help make it compatible?

**Comment by mwesterhof** [comment]
looks like there's no issues with 2.9 support. I released a new version with updated requirements. @sonnybaker please let me know if you run into any issues
