### ISSUE TITLE
Wagtail 2.7 support

### ISSUE THREAD

**Issue by sonnybaker** [mwesterhof/wagtail_app_pages#5]
* Wagtail App Pages version: 0.2.11
* Wagtail version: 2.7+
* Python version: 3.6
* Operating System: Ubuntu

### Description

It's not possible to update a site that uses Wagtail App Pages to version 2.7 of Wagtail because the dependencies specify `<2.7`:

```
wagtail-app-pages (0.2.12) depends on wagtail (>=1.11.1,<2.7), wagtail-app-pages (>0.2.11,<0.3.0) requires wagtail (>=1.11.1,<2
.7).
```

Is there anything blocking App Pages working with Wagtail 2.7, or any way I can help make it compatible?

**Comment by mwesterhof** [comment]
@sonnybaker thanks for the heads up. I've just updated the tox config to include testing on 2.7. I haven't found any problems, so i included it in the officially supported versions. Please upgrade to 0.2.13 and let me know if you run into any problems

**Comment by sonnybaker** [comment]
All good here, thanks for the swift response @mwesterhof
